site_name: Портфолио лабораторных работ
site_description: Сайт-портфолио по лабораторным работам
site_author: Олег Брискиндов

theme:
  name: readthedocs
  language: ru

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Общая страница: labs/index.md
      - Лабораторная работа 1: labs/lab1.md
      - Лабораторная работа 2: labs/lab2.md
      - Лабораторная работа 3: labs/lab3.md